services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    restart: always
    volumes:
      - ./db/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "/app/wait-for-it.sh db:5432 --timeout=60 -- 
            python /app/src/manage.py makemigrations &&
            python /app/src/manage.py migrate &&
            uvicorn src.main:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile  # This builds the React app and serves it with Nginx
    container_name: frontend
    restart: always
    ports:
      - "80:80"  # Serve the static files via Nginx
    depends_on:
      - backend

volumes:
  postgres_data:
