services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    volumes:
      - ./db/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "./wait-for-it.sh db:5432 -- python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"

volumes:
  postgres_data:
